version: '3.8'

services:
  database:
    container_name: ApiPlatformMultiTenancyDatabase
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  php:
    container_name: ApiPlatformMultiTenancyPhp
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/app
    depends_on:
      - database

  nginx:
    container_name: ApiPlatformMultiTenancyNginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
